GuardDuty rolll-out seems to be working.

diff --git a/aws-account-security-setup.yml b/aws-account-security-setup.yml
--- a/aws-account-security-setup.yml
+++ b/aws-account-security-setup.yml
@@ -27,8 +27,32 @@
     when: security_account is defined
     tags: [ 'security', 'securityaccount' ]
 
-  ### This section creates a security CloudFormation Stack on all accounts
-  - name: Block for security setup on the subaccounts
+  - name: Block for guardduty setup on the security account
+    block:
+      - name: Assume role for security/admin
+        sts_assume_role:
+          role_arn: "arn:aws:iam::{{ security_account.account_id }}:role/{{ security_account.sts_role | default('OrganizationAccountAccessRole') }}"
+          role_session_name: "security-{{ security_account.name }}-{{ security_account.sts_role | default('OrganizationAccountAccessRole') }}"
+        register: security_assumed_role
+      - name: Create CFN template from Ansible template for the GuardDuty setup on the security account
+        template:
+          src: "CloudFormationTemplates/cfn-security-account-guardduty-setup.yml"
+          dest: "{{ generated_files_dir | default('generated-files') }}/cfn-{{ organization.name }}-security-account-guardduty-setup.yml"
+      - name: Create or Update the guardduty security account setup Stack
+        cloudformation:
+          aws_access_key: "{{ security_assumed_role.sts_creds.access_key }}"
+          aws_secret_key: "{{ security_assumed_role.sts_creds.secret_key }}"
+          security_token: "{{ security_assumed_role.sts_creds.session_token }}"
+          stack_name: "{{ cfn_org_name }}GuardDuty"
+          state: "present"
+          disable_rollback: false
+          template: "{{ generated_files_dir | default('generated-files') }}/cfn-{{ organization.name }}-security-account-guardduty-setup.yml"
+
+    when: security_account is defined
+    tags: [ 'security', 'security_guardduty' ]
+
+  ### Create CFN templates from AWS templates
+  - name: Set-up credentials
     block:
       - name: Assume Role on all accounts
         sts_assume_role:
@@ -37,6 +61,12 @@
         register: "security_assumed_role_subaccount_single"
         with_items: "{{ lookup('template', 'all_accounts.txt.j2').split(' ') }}"
 
+    when: security_account is defined
+    tags: [ 'always' ]
+
+  ### This section creates a security CloudFormation Stack on all accounts
+  - name: Block for security setup on the subaccounts
+    block:
       - name: Create CFN template from Ansible template for the security setup on the subaccounts
         template:
           src: "CloudFormationTemplates/cfn-security-for-subaccount.yml"
@@ -104,6 +134,7 @@
 
 
  #### GuardDuty Stack
+ ## - name: Determine the GuardDuty DetectorId for the security account, required to get member status
   - name: Block for GuardDuty setup on the security account
     block:
       - name: Get GuardDuty invitation ID
@@ -125,29 +156,50 @@
         retries: 300
         with_items: "{{ guardduty_invitation_id.results | default([]) }}"
 
+#      - debug:
+#          var: "guardduty_invitation_id_jobs"
+
+      - name: Create CFN template from Ansible template for the GuardDuty setup on the subaccounts
+        template:
+          src: "CloudFormationTemplates/cfn-guardduty-for-subaccount.yml"
+          dest: "{{ generated_files_dir | default('generated-files') }}/cfn-{{ organization.name }}-guardduty-for-subaccount-{{ item.item.item.item }}.yml"
+        with_items: "{{ guardduty_invitation_id_jobs.results }}"
+
 
       - name: Create/Update GuardDuty CloudFormation Stack on all accounts
         cloudformation:
-          aws_access_key: "{{ item.item.sts_creds.access_key }}"
-          aws_secret_key: "{{ item.item.sts_creds.secret_key }}"
-          security_token: "{{ item.item.sts_creds.session_token }}"
-          stack_name: "{{ cfn_org_name }}SecuritySubaccount"
+          aws_access_key: "{{ item.item.item.sts_creds.access_key }}"
+          aws_secret_key: "{{ item.item.item.sts_creds.secret_key }}"
+          security_token: "{{ item.item.item.sts_creds.session_token }}"
+          stack_name: "{{ cfn_org_name }}GuarddutySubaccount"
           state: "present"
           disable_rollback: false
-          template: "{{ generated_files_dir | default('generated-files') }}/cfn-{{ organization.name }}-guardduty-for-subaccount-{{ item.item.item }}.yml"
+          template: "{{ generated_files_dir | default('generated-files') }}/cfn-{{ organization.name }}-guardduty-for-subaccount-{{ item.item.item.item }}.yml"
+        when: "item.item.item.item != security_account.account_id"
         with_items:
-          - "{{ guardduty_invitation_id.results }}"
-        register: async_createguarddutycloudformationstack
-        async: 7200
-        poll: 0
-      - name: Wait for async_createguarddutycloudformationstack tasks to finish
-        async_status: jid={{ item.ansible_job_id }}
-        register: async_createguarddutycloudformationstack_jobs
-        until: async_createguarddutycloudformationstack_jobs.finished
-        retries: 300
-        with_items: "{{ async_createguarddutycloudformationstack.results | default([]) }}"
+          - "{{ guardduty_invitation_id_jobs.results }}"
 
+      - name: Accept the invitation
+        shell: |
+          DETECTOR_ID=$(aws guardduty list-detectors --query 'DetectorIds[*]' --output text)
+          [[ -z ${DETECTOR_ID} ]] && { echo "ERROR - No DetectorID - exiting"; exit 1; }
+          set -- $(aws guardduty get-master-account --detector-id ${DETECTOR_ID} --output text)
+          if [[ ${5} == "Enabled" ]]
+          then
+            echo "INFO - Relationship is enabled"
+            exit 0
+          else
+            INVITATION_ID=$(aws guardduty list-invitations --query 'Invitations[*].InvitationId' --output text)
+            [[ -z ${INVITATION_ID} ]] && { echo "ERROR - No InvitationID - exiting"; exit 1; }
+            aws guardduty accept-invitation --detector-id ${DETECTOR_ID} --invitation-id ${INVITATION_ID} --master-id {{ security_account.account_id }}
+          fi
+        environment:
+          AWS_ACCESS_KEY_ID: "{{ item.sts_creds.access_key }}"
+          AWS_SECRET_ACCESS_KEY: "{{ item.sts_creds.secret_key }}"
+          AWS_SESSION_TOKEN: "{{ item.sts_creds.session_token }}"
+          AWS_DEFAULT_REGION: "{{ item.region | default('eu-central-1') }}"
+        with_items: "{{ security_assumed_role_subaccount_single.results }}"
 
     # TODO: Remove the false condition when this is ready
-    when: "false and security_account is defined"
+    when: "security_account is defined"
     tags: [ 'security', 'security_guardduty' ]
